# Form implementation generated from reading ui file 'C:\Users\s.raghavan\OneDrive\Desktop\LN\programming\python\ibm_project\ibm_prj.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import sys
import cv2
import numpy as np
from PyQt6.QtWidgets import QMessageBox


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(940, 376)
        self.title = QtWidgets.QLabel(parent=Dialog)
        self.title.setGeometry(QtCore.QRect(320, 20, 311, 51))
        self.title.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.title.setObjectName("title")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 80, 451, 281))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.e_title = QtWidgets.QLabel(parent=self.frame)
        self.e_title.setGeometry(QtCore.QRect(16, 10, 421, 31))
        self.e_title.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.e_title.setObjectName("e_title")
        self.e_path_l = QtWidgets.QLabel(parent=self.frame)
        self.e_path_l.setGeometry(QtCore.QRect(10, 70, 81, 31))
        self.e_path_l.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.e_path_l.setObjectName("e_path_l")
        self.e_pass_l = QtWidgets.QLabel(parent=self.frame)
        self.e_pass_l.setGeometry(QtCore.QRect(10, 150, 81, 31))
        self.e_pass_l.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.e_pass_l.setObjectName("e_pass_l")
        self.e_path = QtWidgets.QLineEdit(parent=self.frame)
        self.e_path.setGeometry(QtCore.QRect(120, 70, 321, 31))
        self.e_path.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.e_path.setObjectName("e_path")
        self.message = QtWidgets.QLineEdit(parent=self.frame)
        self.message.setGeometry(QtCore.QRect(120, 110, 321, 31))
        self.message.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.message.setObjectName("message")
        self.e_pushButton = QtWidgets.QPushButton(parent=self.frame)
        self.e_pushButton.setGeometry(QtCore.QRect(180, 230, 81, 41))
        self.e_pushButton.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.e_pushButton.setObjectName("e_pushButton")
        self.e_pass = QtWidgets.QLineEdit(parent=self.frame)
        self.e_pass.setGeometry(QtCore.QRect(120, 150, 321, 31))
        self.e_pass.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.e_pass.setObjectName("e_pass")
        self.message_l = QtWidgets.QLabel(parent=self.frame)
        self.message_l.setGeometry(QtCore.QRect(10, 110, 81, 31))
        self.message_l.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.message_l.setObjectName("message_l")
        self.o_path = QtWidgets.QLineEdit(parent=self.frame)
        self.o_path.setGeometry(QtCore.QRect(120, 190, 321, 31))
        self.o_path.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.o_path.setObjectName("o_path")
        self.o_path_l = QtWidgets.QLabel(parent=self.frame)
        self.o_path_l.setGeometry(QtCore.QRect(10, 190, 81, 31))
        self.o_path_l.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.o_path_l.setObjectName("o_path_l")
        self.frame_2 = QtWidgets.QFrame(parent=Dialog)
        self.frame_2.setGeometry(QtCore.QRect(480, 80, 451, 251))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.D_title = QtWidgets.QLabel(parent=self.frame_2)
        self.D_title.setGeometry(QtCore.QRect(16, 10, 421, 31))
        self.D_title.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.D_title.setObjectName("D_title")
        self.d_path_l = QtWidgets.QLabel(parent=self.frame_2)
        self.d_path_l.setGeometry(QtCore.QRect(10, 70, 81, 31))
        self.d_path_l.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.d_path_l.setObjectName("d_path_l")
        self.d_pass_l = QtWidgets.QLabel(parent=self.frame_2)
        self.d_pass_l.setGeometry(QtCore.QRect(10, 110, 81, 31))
        self.d_pass_l.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.d_pass_l.setObjectName("d_pass_l")
        self.d_path = QtWidgets.QLineEdit(parent=self.frame_2)
        self.d_path.setGeometry(QtCore.QRect(120, 70, 321, 31))
        self.d_path.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.d_path.setObjectName("d_path")
        self.d_pass = QtWidgets.QLineEdit(parent=self.frame_2)
        self.d_pass.setGeometry(QtCore.QRect(120, 110, 321, 31))
        self.d_pass.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.d_pass.setObjectName("d_pass")
        self.d_pushButton = QtWidgets.QPushButton(parent=self.frame_2)
        self.d_pushButton.setGeometry(QtCore.QRect(190, 150, 81, 41))
        self.d_pushButton.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.d_pushButton.setObjectName("d_pushButton")
        self.output_d = QtWidgets.QLabel(parent=self.frame_2)
        self.output_d.setGeometry(QtCore.QRect(20, 210, 421, 31))
        self.output_d.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.output_d.setObjectName("output_d")
        self.e_pushButton.clicked.connect(self.encrypt_image)
        self.d_pushButton.clicked.connect(self.decrypt_image)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def encrypt_image(self):
        message = self.message.text()
        password = self.e_pass.text()
        if not message or not password:
            QMessageBox.warning(
                None, "Error", "Message and password cannot be empty!")
            return
        img = cv2.imread(self.e_path.text())
        if img is None:
            QMessageBox.warning(
                None, "Error", "Image not found or cannot be read.")
            return
        if self.o_path == " ":
            QMessageBox.warning(None, "Error", "Output path cannot be empty.")
            return
        if ".png" not in self.o_path.text():
            QMessageBox.warning(
                None, "Error", "Output path must be in .png format.")
            return
        output_path = self.o_path.text()
        n, m, z = 0, 0, 0
        img[n, m, z] = np.uint8(len(password))
        img[n + 1, m + 1, (z + 1) % 3] = np.uint8(len(message))
        n += 2
        m += 2
        z = (z + 2) % 3
        for char in password + message:
            img[n, m, z] = np.uint8(ord(char))
            n += 1
            m += 1
            z = (z + 1) % 3
        cv2.imwrite(output_path, img)
        QMessageBox.information(None, "Result", f"Success {output_path}")

    def decrypt_image(self):
        password_attempt = self.d_pass.text()
        if not password_attempt:
            QMessageBox.warning(
                None, "Error", "Please enter the password to decrypt!")
            return
        if self.d_path == " ":
            QMessageBox.warning(None, "Error", "Output path cannot be empty.")
            return
        image_path = self.d_path.text()
        img = cv2.imread(image_path)
        if img is None:
            QMessageBox.warning(None, "Error", "Encrypted image not found.")
            return
        n, m, z = 0, 0, 0
        password_length = int(img[n, m, z])
        message_length = int(img[n + 1, m + 1, (z + 1) % 3])
        n += 2
        m += 2
        z = (z + 2) % 3
        extracted_password = ""
        for _ in range(password_length):
            extracted_password += chr(int(img[n, m, z]))
            n += 1
            m += 1
            z = (z + 1) % 3
        if extracted_password != password_attempt:
            QMessageBox.warning(
                None, "Error", "Incorrect password! Access denied.")
            return
        message = ""
        for _ in range(message_length):
            message += chr(int(img[n, m, z]))
            n += 1
            m += 1
            z = (z + 1) % 3
        self.output_d.setText(f"Secret Message: {message}")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate(
            "Dialog", "<html><head/><body><p align=\"center\">Stenganography(Image Encryption)</p></body></html>"))
        self.e_title.setText(_translate(
            "Dialog", "<html><head/><body><p align=\"center\">Encryption</p></body></html>"))
        self.e_path_l.setText(_translate(
            "Dialog", "<html><head/><body><p>File Path</p></body></html>"))
        self.e_pass_l.setText(_translate(
            "Dialog", "<html><head/><body><p>Password</p></body></html>"))
        self.e_path.setPlaceholderText(_translate(
            "Dialog", "Enter the path of the image"))
        self.message.setPlaceholderText(_translate(
            "Dialog", "Enter the text to be encrypted"))
        self.e_pushButton.setText(_translate("Dialog", "Encrypt"))
        self.e_pass.setPlaceholderText(
            _translate("Dialog", "Enter the password"))
        self.message_l.setText(_translate("Dialog", "Text"))
        self.o_path.setPlaceholderText(
            _translate("Dialog", "Enter Output Path"))
        self.o_path_l.setText(_translate("Dialog", "Output path"))
        self.D_title.setText(_translate(
            "Dialog", "<html><head/><body><p align=\"center\">Decryption</p></body></html>"))
        self.d_path_l.setText(_translate(
            "Dialog", "<html><head/><body><p>File Path</p></body></html>"))
        self.d_pass_l.setText(_translate(
            "Dialog", "<html><head/><body><p>Password</p></body></html>"))
        self.d_path.setPlaceholderText(_translate(
            "Dialog", "Enter the path of the image"))
        self.d_pass.setPlaceholderText(
            _translate("Dialog", "Enter the password"))
        self.d_pushButton.setText(_translate("Dialog", "Decrypt"))
        self.output_d.setText(_translate(
            "Dialog", "<html><head/><body><p align=\"center\">message will be displayed here</p></body></html>"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
